In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

data1= pd.read_csv('Train.csv')
data1.head()

text sentiment
0   oh Marly, I`m so sorry!!  I hope you find her...   neutral
1  Playing Ghost Online is really interesting. Th...  positive
2  is cleaning the house for her family who is co...   neutral
3  gotta restart my computer .. I thought Win7 wa...   neutral
4  SEe waT I Mean bOuT FoLL0w fRiiDaYs... It`S cA...   neutral

In [2]:
data1.isnull().values.any()
data1= data1.dropna()
data1=data1.reindex(range(27447))
data1

text sentiment
0       oh Marly, I`m so sorry!!  I hope you find her...   neutral
1      Playing Ghost Online is really interesting. Th...  positive
2      is cleaning the house for her family who is co...   neutral
3      gotta restart my computer .. I thought Win7 wa...   neutral
4      SEe waT I Mean bOuT FoLL0w fRiiDaYs... It`S cA...   neutral
5      the free fillin` app on my ipod is fun, im add...  positive
6                                             I`m sorry.  negative
7      On the way to Malaysia...no internet access to...  negative
8      juss came backk from Berkeleyy ; omg its madd ...  positive
9      Went to sleep and there is a power cut in Noid...  negative
10     I`m going home now. Have you seen my new twitt...  positive
11     i hope unni will make the audition . fighting ...  positive
12      If it is any consolation I got my BMI tested ...  negative
13                        That`s very funny.  Cute kids.  positive
14      Ahhh, I slept through the game.  I`m gonna tr...   neutral
15     Thats it, its the end. Tears for Fears vs Eric...   neutral
16     Born and raised in NYC and living in Texas for...  negative
17     just in case you wonder, we are really busy to...   neutral
18     i`m soooooo sleeeeepy!!! the last day o` schoo...  negative
19     A little happy for the wine jeje ok it`sm my f...  positive
20      Car not happy, big big dent in boot! Hoping t...   neutral
21     im an avid fan of **** magazine and i love you...  positive
22                                              MAYDAY?!   neutral
23     RATT ROCKED NASHVILLE TONITE..ONE THING SUCKED...   neutral
24      I love to! But I`m only available from 5pm.  ...  positive
25     The girl in the hair salon asked me 'Shall I t...   neutral
26     egh blah and boooooooooooo i dunno wanna go to...  negative
27                  :visiting my friendster and facebook   neutral
28     i donbt like to peel prawns, i also dont like ...  negative
29      which case? I got a new one last week and I`m...  negative
...                                                  ...       ...
27417   I would never do such a thing!  The only thin...   neutral
27418                Where is my bestie when i need him   negative
27419       I am beginning to think sun blcok is a haox.  negative
27420      I GET IT.  YOU ESPLAINED IT TO ME AWHILE AGO.  negative
27421   Wanted to get that piercing too but thought i...   neutral
27422   staying in, hve June exams 4 docent training ...   neutral
27423   Yes! I love him. I have seen the eps so many ...  positive
27424  Ps Brian just announced his message title, 'wh...   neutral
27425   Yup, sometimes kc it`s raining here in Pque b...   neutral
27426   i am glad cos u wouldnt lose me as a fan anyw...  positive
27427  is having carbonara for dinner made by my mum mom   neutral
27428    but that is the only logical reason why you`...   neutral
27429                   haha malamang as one of my chef.   neutral
27430                     did you find the Colossus yet?   neutral
27431   happy all my studying and all nighters payed off  positive
27432  so much for a day off- I`ve been on my feet, a...   neutral
27433                               it`s beeen onee year   neutral
27434  _mayer I`d like to see a picture of you, Carl ...  positive
27435  simple greetings from unexpected people can ac...  positive
27436     i wanna leave work already! Not feelin it 2day  negative
27437                              My camera is brokennn   neutral
27438  I really wish someone would make a groupchat t...  positive
27439                          good as, cya in melbourne  positive
27440  Scream just played on my iPod. First thing tha...   neutral
27441   again thanks to my dear neighboor who also ga...  positive
27442  Just back from bingo w/family -- I won over $1...  positive
27443   LIKE DREW SAID 'GIVE TC A CHANCE' WE WILL MIS...  negative
27444  rec game....trying not to cry...the pain is to...  negative
27445   Sure. I`ll try n keep th

In [3]:
#converting everyting to lower case
df= data1.copy()
df= df.apply(lambda x: x.astype(str).str.lower())

df['text']   

0         oh marly, i`m so sorry!!  i hope you find her...
1        playing ghost online is really interesting. th...
2        is cleaning the house for her family who is co...
3        gotta restart my computer .. i thought win7 wa...
4        see wat i mean bout foll0w friidays... it`s ca...
5        the free fillin` app on my ipod is fun, im add...
6                                               i`m sorry.
7        on the way to malaysia...no internet access to...
8        juss came backk from berkeleyy ; omg its madd ...
9        went to sleep and there is a power cut in noid...
10       i`m going home now. have you seen my new twitt...
11       i hope unni will make the audition . fighting ...
12        if it is any consolation i got my bmi tested ...
13                          that`s very funny.  cute kids.
14        ahhh, i slept through the game.  i`m gonna tr...
15       thats it, its the end. tears for fears vs eric...
16       born and raised in nyc and living in texas for.

In [4]:
import string
#symbols = "!\"#$%&()*+-./:;<=>?@[\]^_`{|}~\n"

#this is for removing punctutations
def remove_punctuations(text):
    for punctuation in string.punctuation:
        text = text.replace(punctuation, '')
    return text
for i in range(27447):
    df['text'][i]= remove_punctuations(df['text'][i])

df['text']


0         oh marly im so sorry  i hope you find her soo...
1        playing ghost online is really interesting the...
2        is cleaning the house for her family who is co...
3        gotta restart my computer  i thought win7 was ...
4        see wat i mean bout foll0w friidays its called...
5        the free fillin app on my ipod is fun im addicted
6                                                 im sorry
7         on the way to malaysiano internet access to twit
8        juss came backk from berkeleyy  omg its madd f...
9        went to sleep and there is a power cut in noid...
10       im going home now have you seen my new twitter...
11       i hope unni will make the audition  fighting d...
12        if it is any consolation i got my bmi tested ...
13                             thats very funny  cute kids
14        ahhh i slept through the game  im gonna try m...
15       thats it its the end tears for fears vs eric p...
16       born and raised in nyc and living in texas for.

In [5]:
#this code is to remove any digit that may appear in the text.
for i in range(27447):
    df['text'][i] = ''.join([j for j in df['text'][i] if not j.isdigit()])
        
df['text']

0         oh marly im so sorry  i hope you find her soon  
1        playing ghost online is really interesting the...
2        is cleaning the house for her family who is co...
3        gotta restart my computer  i thought win was s...
4        see wat i mean bout follw friidays its called ...
5        the free fillin app on my ipod is fun im addicted
6                                                 im sorry
7         on the way to malaysiano internet access to twit
8        juss came backk from berkeleyy  omg its madd f...
9        went to sleep and there is a power cut in noid...
10       im going home now have you seen my new twitter...
11       i hope unni will make the audition  fighting d...
12        if it is any consolation i got my bmi tested ...
13                             thats very funny  cute kids
14        ahhh i slept through the game  im gonna try m...
15       thats it its the end tears for fears vs eric p...
16       born and raised in nyc and living in texas for.

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

df['sentiment']=df['sentiment'].map({'positive':0,'neutral':1,'negative':2})

# create the transform
vectorizer = TfidfVectorizer()
df= df.dropna()
# tokenize and build vocab
vectorizer.fit_transform(df['text'])
y= df['sentiment']
y


0        1.0
1        0.0
2        1.0
3        1.0
4        1.0
5        0.0
6        2.0
7        2.0
8        0.0
9        2.0
10       0.0
11       0.0
12       2.0
13       0.0
14       1.0
15       1.0
16       2.0
17       1.0
18       2.0
19       0.0
20       1.0
21       0.0
22       1.0
23       1.0
24       0.0
25       1.0
26       2.0
27       1.0
28       2.0
29       2.0
        ... 
27417    1.0
27418    2.0
27419    2.0
27420    2.0
27421    1.0
27422    1.0
27423    0.0
27424    1.0
27425    1.0
27426    0.0
27427    1.0
27428    1.0
27429    1.0
27430    1.0
27431    0.0
27432    1.0
27433    1.0
27434    0.0
27435    0.0
27436    2.0
27437    1.0
27438    0.0
27439    0.0
27440    1.0
27441    0.0
27442    0.0
27443    2.0
27444    2.0
27445    0.0
27446    1.0
Name: sentiment, Length: 27446, dtype: float64

In [7]:
vector = vectorizer.transform(df['text'].values)
vector.shape
X= vector


In [8]:
#the first model is using svm 

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report,accuracy_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2)
model= SVC(kernel='linear')
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test,y_pred))

[[1753  748   79]
 [ 355 2570  347]
 [ 117  893 1372]]
              precision    recall  f1-score   support

         0.0       0.79      0.68      0.73      2580
         1.0       0.61      0.79      0.69      3272
         2.0       0.76      0.58      0.66      2382

    accuracy                           0.69      8234
   macro avg       0.72      0.68      0.69      8234
weighted avg       0.71      0.69      0.69      8234

0.6916444012630556


In [10]:
#this is logistic regression model

In [11]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(solver='liblinear').fit(X_train, y_train)
y_pred = clf.predict(X_test)

print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))



0.6774350255040078
[[1709  784   87]
 [ 366 2558  348]
 [ 112  959 1311]]
              precision    recall  f1-score   support

         0.0       0.78      0.66      0.72      2580
         1.0       0.59      0.78      0.68      3272
         2.0       0.75      0.55      0.64      2382

    accuracy                           0.68      8234
   macro avg       0.71      0.66      0.68      8234
weighted avg       0.70      0.68      0.68      8234



In [12]:
#the next is doing logistic regression with cross validation

In [13]:
from sklearn.model_selection import cross_val_score, KFold
logreg = LogisticRegression(solver= 'lbfgs',max_iter=10000,random_state=2)
print(cross_val_score(logreg, X_train, y_train, cv=5, scoring='accuracy').mean())


0.67338101157577


In [14]:
#accuracy from svm- 0.69
#accuracy from linear logistic regression- 0.68
#accracy from logistic regression cross validation- 0.67